# Generated by Django 2.1.1 on 2018-09-20 01:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('word_search', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='puzzle',
            old_name='creation_Date',
            new_name='creationDate',
        ),
    ]
