# Generated by Django 2.1.1 on 2018-09-20 02:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('word_search', '0002_auto_20180919_2158'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wordlist',
            name='puzzle',
        ),
        migrations.AlterField(
            model_name='word',
            name='wordList',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='word_search.Puzzle'),
        ),
        migrations.DeleteModel(
            name='WordList',
        ),
    ]
