# Generated by Django 2.1.1 on 2018-09-20 02:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('word_search', '0003_auto_20180919_2236'),
    ]

    operations = [
        migrations.RenameField(
            model_name='word',
            old_name='wordList',
            new_name='puzzle',
        ),
    ]
