# Generated by Django 2.1.1 on 2018-09-20 03:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('word_search', '0004_auto_20180919_2237'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matrix',
            name='puzzle',
        ),
        migrations.RemoveField(
            model_name='row',
            name='matrix',
        ),
        migrations.AddField(
            model_name='puzzle',
            name='length',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='row',
            name='puzzle',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='word_search.Puzzle'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Matrix',
        ),
    ]
